# Generated by Django 5.2.6 on 2025-09-27 21:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainInterface', '0003_course_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('assignment', 'Assignment'), ('quiz', 'Quiz'), ('midterm', 'Midterm Exam'), ('final', 'Final Exam'), ('project', 'Project'), ('participation', 'Participation'), ('final_grade', 'Final Course Grade')], default='assignment', max_length=15)),
                ('grade_value', models.CharField(choices=[('A+', 'A+ (90-100)'), ('A', 'A (85-89)'), ('A-', 'A- (80-84)'), ('B+', 'B+ (77-79)'), ('B', 'B (73-76)'), ('B-', 'B- (70-72)'), ('C+', 'C+ (67-69)'), ('C', 'C (63-66)'), ('C-', 'C- (60-62)'), ('D+', 'D+ (57-59)'), ('D', 'D (53-56)'), ('D-', 'D- (50-52)'), ('F', 'F (0-49)'), ('I', 'Incomplete'), ('W', 'Withdrawal'), ('P', 'Pass'), ('NP', 'No Pass')], max_length=3)),
                ('numeric_score', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric score (0-100)', max_digits=5, null=True)),
                ('max_points', models.DecimalField(decimal_places=2, default=100, help_text='Maximum possible points', max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight of this grade in final calculation', max_digits=5)),
                ('description', models.CharField(blank=True, help_text='Assignment or exam name', max_length=200)),
                ('date_graded', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.TextField(blank=True, help_text='Instructor feedback')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='MainInterface.course')),
                ('student', models.ForeignKey(limit_choices_to={'userprofile__user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['-date_graded'],
            },
        ),
    ]
