# Generated by Django 5.2.6 on 2025-09-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainInterface', '0005_alter_course_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('semester_start', 'Semester Start'), ('semester_end', 'Semester End'), ('registration_start', 'Registration Start'), ('registration_end', 'Registration End'), ('exam_period', 'Exam Period'), ('holiday', 'Holiday'), ('break', 'Break'), ('deadline', 'Important Deadline'), ('event', 'Special Event')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('semester', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], max_length=20)),
                ('year', models.IntegerField(default=2025)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Academic Calendar Event',
                'verbose_name_plural': 'Academic Calendar Events',
                'ordering': ['start_date'],
            },
        ),
    ]
