# Generated by Django 5.2.6 on 2025-09-30 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainInterface', '0010_course_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional details about the class session')),
                ('class_type', models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Laboratory'), ('tutorial', 'Tutorial'), ('seminar', 'Seminar'), ('workshop', 'Workshop'), ('exam', 'Examination'), ('presentation', 'Presentation'), ('fieldwork', 'Field Work'), ('online', 'Online Session'), ('other', 'Other')], default='lecture', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, help_text='Classroom, lab, or meeting location', max_length=200)),
                ('is_online', models.BooleanField(default=False)),
                ('meeting_url', models.URLField(blank=True, help_text='Online meeting link if applicable')),
                ('max_attendees', models.PositiveIntegerField(blank=True, help_text='Maximum number of attendees (optional)', null=True)),
                ('required_materials', models.TextField(blank=True, help_text='Materials students should bring')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for students')),
                ('is_active', models.BooleanField(default=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='MainInterface.course')),
                ('lecturer', models.ForeignKey(limit_choices_to={'user_type': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_classes', to='MainInterface.userprofile')),
            ],
            options={
                'verbose_name': 'Class Schedule',
                'verbose_name_plural': 'Class Schedules',
                'ordering': ['start_datetime'],
            },
        ),
    ]
