# Generated by Django 5.2.7 on 2025-10-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainInterface', '0011_classschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=2025, help_text='Academic year'),
        ),
    ]
